services:
  - type: web
    name: miniproyecto-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false # Esto permite que pegues la URL de Supabase manualmente en el panel de Render
      - key: SECRET_KEY
        generateValue: true